Advance Numpy

In [1]:
import numpy as np

In [2]:
In [11]: np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [3]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [4]:
arr= np.arange(8)
print(arr)
arr.reshape((4,2))

[0 1 2 3 4 5 6 7]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [5]:
arr.reshape(4,2).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr = np.arange(15)
arr.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Concating and splitting array

In [9]:
In [35]: arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [36]: arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [37]: np.concatenate([arr1, arr2], axis=0) # same as np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
In [37]: np.concatenate([arr1, arr2], axis=1) # same as np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [11]:
first, second, third = np.split(arr, [1, 3])

In [12]:
In [47]: arr = np.arange(6)

In [48]: arr1 = arr.reshape((3, 2))

In [49]: arr2 = np.random.randn(3, 2)

In [50]: np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-1.51320894,  1.35800616],
       [ 0.25164932,  0.35003426],
       [-2.56152284, -0.7299325 ]])

In [13]:
In [51]: np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-1.51320894,  1.35800616,  3.        ],
       [ 0.25164932,  0.35003426,  4.        ],
       [-2.56152284, -0.7299325 ,  5.        ]])

In [14]:
In [52]: np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [15]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [16]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [17]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [18]:
arr= np.random.randn(2,2)
arr

array([[ 1.19036036,  1.47722736],
       [-0.04332168, -1.65591513]])

In [19]:
arr.repeat(2, axis=0)

array([[ 1.19036036,  1.47722736],
       [ 1.19036036,  1.47722736],
       [-0.04332168, -1.65591513],
       [-0.04332168, -1.65591513]])

In [20]:
arr.repeat([2,3], axis=0)

array([[ 1.19036036,  1.47722736],
       [ 1.19036036,  1.47722736],
       [-0.04332168, -1.65591513],
       [-0.04332168, -1.65591513],
       [-0.04332168, -1.65591513]])

In [21]:
arr

array([[ 1.19036036,  1.47722736],
       [-0.04332168, -1.65591513]])

In [22]:
np.tile(arr,2)

array([[ 1.19036036,  1.47722736,  1.19036036,  1.47722736],
       [-0.04332168, -1.65591513, -0.04332168, -1.65591513]])

In [23]:
arr= np.arange(10)*100
inds = [7,1,2,6,1]
arr[inds]

array([700, 100, 200, 600, 100])

In [24]:
arr.take(inds)

array([700, 100, 200, 600, 100])

In [25]:
arr.put(inds,42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [26]:
In [75]: inds = [2, 0, 2, 1]

In [76]: arr = np.random.randn(2, 4)

In [77]: arr

array([[-1.47034099, -0.00641698, -0.96754217,  1.01234932],
       [-0.64132057, -1.34484836, -2.80884109, -0.7695558 ]])

In [27]:
In [78]: arr.take(inds, axis=1)

array([[-0.96754217, -1.47034099, -0.96754217, -0.00641698],
       [-2.80884109, -0.64132057, -2.80884109, -1.34484836]])

In [28]:
arr= np.random.randn(4,3)
print(arr)
arr.mean(0)

[[-0.62522772  0.88076237 -0.12383925]
 [ 1.18913114 -0.54097702 -1.00712508]
 [ 0.43312427 -0.39931715 -1.35544594]
 [-1.68113882 -0.16672375 -0.46273709]]


array([-0.17102778, -0.05656389, -0.73728684])

In [29]:
demeaned = arr-arr.mean(0)
demeaned

array([[-0.45419994,  0.93732626,  0.61344759],
       [ 1.36015892, -0.48441314, -0.26983824],
       [ 0.60415205, -0.34275326, -0.6181591 ],
       [-1.51011104, -0.11015986,  0.27454975]])

In [30]:
arr

array([[-0.62522772,  0.88076237, -0.12383925],
       [ 1.18913114, -0.54097702, -1.00712508],
       [ 0.43312427, -0.39931715, -1.35544594],
       [-1.68113882, -0.16672375, -0.46273709]])

In [31]:
row_means = arr.mean(1)

In [32]:
row_means.shape

(4,)

In [33]:
row_means.reshape(4,1)

array([[ 0.04389847],
       [-0.11965699],
       [-0.44054627],
       [-0.77019989]])

In [34]:
In [91]: demeaned = arr - row_means.reshape((4, 1))

In [92]: demeaned.mean(1)

array([-9.25185854e-18,  3.70074342e-17, -7.40148683e-17, -3.70074342e-17])

In [35]:
In [94]: arr - arr.mean(1).reshape((4, 1))

array([[-0.66912619,  0.8368639 , -0.16773772],
       [ 1.30878813, -0.42132004, -0.88746809],
       [ 0.87367054,  0.04122913, -0.91489967],
       [-0.91093893,  0.60347614,  0.3074628 ]])

In [36]:
In [95]: arr = np.zeros((4, 4))

In [96]: arr_3d = arr[:, np.newaxis, :]
print(arr_3d)
In [97]: arr_3d.shape

[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]


(4, 1, 4)

In [37]:
In [98]: arr_1d = np.random.normal(size=3)

In [99]: arr_1d[:, np.newaxis]

array([[0.76547491],
       [0.49063664],
       [0.09990604]])

In [38]:
In [100]: arr_1d[np.newaxis, :]

array([[0.76547491, 0.49063664, 0.09990604]])

In [39]:
In [101]: arr = np.random.randn(3, 4, 5)

In [102]: depth_means = arr.mean(2)
print(arr)
In [103]: depth_means

[[[ 0.41416094 -0.21003052 -0.34203362 -0.93507258  0.13133642]
  [ 0.091654   -1.53830527 -1.32137382  1.4245857   1.04886998]
  [ 0.61393464  2.18720371 -0.63591864  0.30777752 -0.20881916]
  [ 0.71093789  0.87061252 -0.32368454 -0.01320645 -1.12376381]]

 [[ 0.411575    1.01440382 -0.91811388 -0.86360054 -0.16548275]
  [ 0.23110525  1.23906609  1.55472026  1.69008052  0.48924353]
  [-1.05869593  0.16435106  2.28943514 -0.27094952  0.69701845]
  [-0.14851843 -0.75952293  1.4503227  -0.20400084 -0.30011208]]

 [[ 0.1632164   0.55424969 -0.90277906  0.50408379  0.01962925]
  [-2.4799242  -1.93996044  1.02811396 -1.82017865 -1.06581198]
  [-0.87831304 -0.17279572 -0.81671349  0.12857735 -0.1409297 ]
  [-0.83298434 -0.0425637  -0.075971    0.18107783  0.49149563]]]


array([[-0.18832787, -0.05891388,  0.45283561,  0.02417912],
       [-0.10424367,  1.04084313,  0.36423184,  0.00763368],
       [ 0.06768002, -1.25555226, -0.37603492, -0.05578911]])

In [40]:
depth_means.shape

(3, 4)

In [41]:
In [105]: demeaned = arr - depth_means[:, :, np.newaxis]

In [106]: demeaned.mean(2)

array([[ 2.22044605e-17, -8.88178420e-17,  4.44089210e-17,
         0.00000000e+00],
       [-2.22044605e-17, -1.55431223e-16, -4.44089210e-17,
        -2.22044605e-17],
       [ 6.93889390e-18,  4.44089210e-17, -5.55111512e-18,
        -2.22044605e-17]])

In [42]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalizes things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

In [43]:
In [107]: arr = np.zeros((4, 3))
In [108]: arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [44]:
In [110]: col = np.array([1.28, -0.42, 0.44, 1.6])

In [111]: arr[:] = col[:, np.newaxis]

In [112]: arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [45]:

In [113]: arr[:2] = [[-1], [1]]

In [114]: arr

array([[-1.  , -1.  , -1.  ],
       [ 1.  ,  1.  ,  1.  ],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [46]:
In [115]: arr = np.arange(10)
print(arr)
In [116]: np.add.reduce(arr)

[0 1 2 3 4 5 6 7 8 9]


45

In [53]:
In [118]: np.random.seed(12346)  # for reproducibility

In [119]: arr = np.random.randn(5, 5)

In [120]: arr[::2].sort(1) # sort a few rows
print(arr[:, :-1])
print("\n")
print(arr[:, 1:])
In [121]: arr[:, :-1] < arr[:, 1:]

[[-9.81497953e-01 -8.99822478e-02  3.65775545e-01  7.48336101e-01]
 [-3.15442628e-01 -8.66135605e-01  2.78568155e-02 -4.55597723e-01]
 [-8.48730755e-01 -5.46459347e-01 -3.21536673e-01  4.60468309e-04]
 [ 2.53915229e-01  1.93684246e+00 -7.99504902e-01 -5.69159281e-01]
 [-9.53521432e-01 -6.49092950e-01 -4.79535727e-01  1.75403128e-01]]


[[-8.99822478e-02  3.65775545e-01  7.48336101e-01  7.59372617e-01]
 [-8.66135605e-01  2.78568155e-02 -4.55597723e-01 -1.60189223e+00]
 [-5.46459347e-01 -3.21536673e-01  4.60468309e-04  2.48256116e-01]
 [ 1.93684246e+00 -7.99504902e-01 -5.69159281e-01  4.89244731e-02]
 [-6.49092950e-01 -4.79535727e-01  1.75403128e-01  1.42253882e+00]]


array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
arr= np.arange(15).reshape(3,5)
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [55]:
In [125]: arr = np.arange(3).repeat([1, 2, 2])

In [126]: arr

array([0, 1, 1, 2, 2])

In [56]:
In [127]: np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [57]:
In [131]: arr = np.arange(10)

In [132]: np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [58]:
In [136]: def add_elements(x, y):
   .....:     return x + y

In [137]: add_them = np.frompyfunc(add_elements, 2, 1)

In [138]: add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [59]:
In [139]: add_them = np.vectorize(add_elements, otypes=[np.float64])

In [140]: add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [60]:
In [141]: arr = np.random.randn(10000)

In [142]: %timeit add_them(arr, arr)

1.29 ms ± 37.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [61]:

In [143]: %timeit np.add(arr, arr)

4.15 µs ± 61.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [62]:
In [144]: dtype = [('x', np.float64), ('y', np.int32)]

In [145]: sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)

In [146]: sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [63]:
sarr[0]['y']

6

In [64]:
sarr['x']

array([1.5       , 3.14159265])

In [65]:
In [155]: dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]

In [156]: data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)

In [157]: data['x']

array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [66]:
In [159]: data['x']['a']

array([1., 3.])

In [67]:
values = np.array([5,0,1,3,2])
In [177]: indexer = values.argsort()

In [178]: indexer

array([1, 2, 4, 3, 0])

In [68]:
values[indexer]

array([0, 1, 2, 3, 5])

In [69]:
In [180]: arr = np.random.randn(3, 5)

In [181]: arr[0] = values

In [182]: arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 1.06008044, -1.69901085, -0.98038019, -1.92113546,  2.07767166],
       [ 1.24606621,  0.16549011,  0.90152081, -0.44887332,  0.18657953]])

In [70]:
In [183]: arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-1.69901085, -0.98038019,  2.07767166, -1.92113546,  1.06008044],
       [ 0.16549011,  0.90152081,  0.18657953, -0.44887332,  1.24606621]])

In [71]:
In [198]: indices = np.argpartition(arr, 3)

In [199]: indices

array([[1, 2, 4, 3, 0],
       [3, 2, 1, 0, 4],
       [3, 4, 1, 2, 0]])

In [72]:
np.argpartition?

Signature: np.argpartition(a, kth, axis=-1, kind='introselect', order=None)
Docstring:
Perform an indirect partition along the given axis using the
algorithm specified by the `kind` keyword. It returns an array of
indices of the same shape as `a` that index data along the given
axis in partitioned order.

.. versionadded:: 1.8.0

Parameters
----------
a : array_like
    Array to sort.
kth : int or sequence of ints
    Element index to partition by. The k-th element will be in its
    final sorted position and all smaller elements will be moved
    before it and all larger elements behind it. The order all
    elements in the partitions is undefined. If provided with a
    sequence of k-th it will partition all of them into their sorted
    position at once.
axis : int or None, optional
    Axis along which to sort. The default is -1 (the last axis). If
    None, the flattened array is used.
kind : {'introselect'}, optional
    Selection algorithm. Default is 'introselect'
order : str o

In [74]:
#x - y).mean() using a for loop
import numpy as np

def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

In [75]:
In [209]: x = np.random.randn(10000000)

In [210]: y = np.random.randn(10000000)

In [212]: %timeit (x - y).mean()

27 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
#numpy version is over 100 time faster

In [76]:
In [213]: import numba as nb

In [214]: numba_mean_distance = nb.jit(mean_distance)

In [77]:
# here is how we can write this in decorator
@nb.jit
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

In [78]:
In [215]: %timeit numba_mean_distance(x, y)

13.6 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [79]:
from numba import float64, njit

@njit(float64(float64[:], float64[:]))
def mean_distance(x, y):
    return (x - y).mean()

Creating Custom numpy.ufunc Objects with Numba

In [80]:
from numba import vectorize

@vectorize
def nb_add(x, y):
    return x + y

In [81]:
In [13]: x = np.arange(10)

In [14]: nb_add(x, x)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
In [15]: nb_add.accumulate(x, 0)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [83]:
In [214]: mmap = np.memmap('mymmap', dtype='float64', mode='w+',
   .....:                  shape=(10000, 10000))

In [215]: mmap

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [85]:
In [216]: section = mmap[:5]
In [217]: section[:] = np.random.randn(5, 10000)

In [218]: mmap.flush()

In [219]: mmap

memmap([[ 0.53013062,  0.8226272 ,  0.82118226, ...,  0.94114474,
          0.98512866,  0.06452979],
        [ 0.04371354,  0.85948309,  0.1031302 , ..., -0.59867873,
          0.01627565, -1.89402861],
        [-0.03328665, -1.49603348, -0.57698861, ..., -1.42257783,
         -0.12287793, -0.40673105],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [86]:
del mmap

In [87]:
In [221]: mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))

In [222]: mmap

memmap([[ 0.53013062,  0.8226272 ,  0.82118226, ...,  0.94114474,
          0.98512866,  0.06452979],
        [ 0.04371354,  0.85948309,  0.1031302 , ..., -0.59867873,
          0.01627565, -1.89402861],
        [-0.03328665, -1.49603348, -0.57698861, ..., -1.42257783,
         -0.12287793, -0.40673105],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [88]:
In [225]: arr_c = np.ones((1000, 1000), order='C')

In [226]: arr_f = np.ones((1000, 1000), order='F')

In [227]: arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [89]:
arr_f.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [90]:
In [230]: %timeit arr_c.sum(1)

367 µs ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [91]:
In [231]: %timeit arr_f.sum(1)

433 µs ± 40.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [92]:
In [232]: arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [93]:
In [233]: arr_c[:50].flags.contiguous

True

In [94]:
In [234]: arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False