In [3]:
import pandas as pd
import numpy as np

from pandas import Series, DataFrame

obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
In [13]: obj.values


In [14]: obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [8]:
In [26]: sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [27]: obj3 = pd.Series(sdata)

In [28]: obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [9]:
In [29]: states = ['California', 'Ohio', 'Oregon', 'Texas']

In [30]: obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [10]:
In [38]: obj4.name = 'population'

In [39]: obj4.index.name = 'state'

In [40]: obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [11]:
In [42]: obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [43]: obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [12]:
data = {'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame.head()

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [13]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [14]:
In [48]: frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
   ....:                       index=['one', 'two', 'three', 'four',
   ....:                              'five', 'six'])

In [49]: frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [15]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [16]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [17]:
In [54]: frame2['debt'] = 16.5

In [55]: frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [18]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [19]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val



In [21]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [22]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [23]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [24]:
In [70]: pdata = {'Ohio': frame3['Ohio'][:-1],
   ....:          'Nevada': frame3['Nevada'][:2]}

In [71]: pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [25]:
In [72]: frame3.index.name = 'year'; frame3.columns.name = 'state'

In [73]: frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [26]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [27]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [28]:
s = ((1,0,0,0,),(2,3,0,0,),(4,5,6,0,),(7,8,9,10,))

print(pd.DataFrame(list(s)))

   0  1  2   3
0  1  0  0   0
1  2  3  0   0
2  4  5  6   0
3  7  8  9  10


In [29]:
In [76]: obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [77]: index = obj.index

In [78]: index

Index(['a', 'b', 'c'], dtype='object')

In [30]:
In [79]: index[1:]

Index(['b', 'c'], dtype='object')

In [31]:
In [80]: labels = pd.Index(np.arange(3))

In [81]: labels

Int64Index([0, 1, 2], dtype='int64')

In [32]:
In [82]: obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [83]: obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [33]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [34]:
2003 in frame3.index

False

In [35]:
In [91]: obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [92]: obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [36]:
In [93]: obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [94]: obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [38]:
In [95]: obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [96]: obj3

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [40]:
In [97]: obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [41]:
In [98]: frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
   ....:                      index=['a', 'c', 'd'],
   ....:                      columns=['Ohio', 'Texas', 'California'])

In [99]: frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [44]:
In [100]: frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [45]:
In [102]: states = ['Texas', 'Utah', 'California']

In [103]: frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [51]:
In [105]: obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [107]: new_obj = obj.drop('c')

In [108]: new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [52]:
In [109]: obj.drop(['d', 'c']) # droping multiple indexes at once.

a    0.0
b    1.0
e    4.0
dtype: float64

In [54]:
In [110]: data = pd.DataFrame(np.arange(16).reshape((4, 4)),
   .....:                     index=['Ohio', 'Colorado', 'Utah', 'New York'],
   .....:                     columns=['one', 'two', 'three', 'four'])

In [111]: data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [55]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [61]:
In [113]: data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [62]:
In [114]: data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [63]:
In [115]: obj.drop('c', inplace=True)

In [116]: obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [64]:
In [117]: obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [118]: obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [65]:
In [125]: obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [66]:
In [126]: obj['b':'c'] = 5

In [127]: obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [67]:
In [128]: data = pd.DataFrame(np.arange(16).reshape((4, 4)),
   .....:                     index=['Ohio', 'Colorado', 'Utah', 'New York'],
   .....:                     columns=['one', 'two', 'three', 'four'])

In [129]: data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [69]:
In [130]: data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [70]:
In [131]: data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [71]:
In [133]: data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [72]:
In [134]: data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [73]:
In [137]: data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [74]:
In [138]: data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [75]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [76]:
In [145]: ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [146]: ser2[-1]

2.0

In [78]:
In [147]: ser2[:1]

a    0.0
dtype: float64

In [83]:
In [150]: s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [151]: s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
   .....:                index=['a', 'c', 'e', 'f', 'g'])

print(s2)
In [152]: s1


a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [80]:
In [154]: s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [84]:
In [155]: df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
   .....:                    index=['Ohio', 'Texas', 'Colorado'])

In [156]: df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
   .....:                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [157]: df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [85]:
In [159]: df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [86]:
In [165]: df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
   .....:                    columns=list('abcd'))

In [166]: df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
   .....:                    columns=list('abcde'))

In [167]: df2.loc[1, 'b'] = np.nan

In [168]: df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [87]:
df1.add(df2, fill_value=0) # very good

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [88]:
In [174]: df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [91]:
In [175]: arr = np.arange(12.).reshape((3, 4))

print(arr[0])
In [176]: arr

[0. 1. 2. 3.]


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [90]:
In [178]: arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [93]:
In [179]: frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
   .....:                      columns=list('bde'),
   .....:                      index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [180]: series = frame.iloc[0]
print(series)
In [181]: frame

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [94]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [95]:
In [184]: series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [185]: frame + series2
    

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [98]:
In [186]: series3 = frame['d']
print(series3)
In [187]: frame

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [97]:
In [189]: frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [99]:
In [190]: frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
   .....:                      index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [191]: frame

b         d         e
Utah    0.682955  0.257663  0.617505
Ohio   -0.232332 -1.114678  1.601558
Texas   0.627021 -0.208454 -1.845482
Oregon -0.562546 -0.292138 -0.790741

In [100]:
In [192]: np.abs(frame)

b         d         e
Utah    0.682955  0.257663  0.617505
Ohio    0.232332  1.114678  1.601558
Texas   0.627021  0.208454  1.845482
Oregon  0.562546  0.292138  0.790741

In [101]:
In [193]: f = lambda x: x.max() - x.min()

In [194]: frame.apply(f)

b    1.245501
d    1.372341
e    3.447040
dtype: float64

In [102]:
In [195]: frame.apply(f, axis='columns')

Utah      0.425292
Ohio      2.716236
Texas     2.472503
Oregon    0.498603
dtype: float64

In [103]:
In [196]: def f(x):
   .....:     return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [197]: frame.apply(f)

b         d         e
min -0.562546 -1.114678 -1.845482
max  0.682955  0.257663  1.601558

In [104]:
In [198]: format = lambda x: '%.2f' % x # two digit after decimal

In [199]: frame.applymap(format)

b      d      e
Utah     0.68   0.26   0.62
Ohio    -0.23  -1.11   1.60
Texas    0.63  -0.21  -1.85
Oregon  -0.56  -0.29  -0.79

In [105]:
In [211]: frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [212]: frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [106]:
In [213]: frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [107]:
In [215]: obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [216]: obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [108]:
In [217]: obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [109]:
In [219]: frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
   .....:                       'c': [-2, 5, 8, -2.5]})

In [220]: frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [110]:
In [221]: frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [111]:
In [222]: obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [223]: obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [112]:
In [224]: obj.index.is_unique

False

In [113]:
In [230]: df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
   .....:                    [np.nan, np.nan], [0.75, -1.3]],
   .....:                   index=['a', 'b', 'c', 'd'],
   .....:                   columns=['one', 'two'])

In [231]: df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [114]:
In [232]: df.sum()

one    9.25
two   -5.80
dtype: float64

In [115]:
In [234]: df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [117]:
import pandas_datareader.data as web

all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

/Users/praladneupane/opt/anaconda3/lib/python3.7/site-packages/pandas_datareader/compat/__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal


In [118]:
In [242]: returns = price.pct_change()

In [243]: returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-05-19 -0.005778 -0.010447 -0.006922 -0.007554
2020-05-20  0.019448  0.009061  0.013871  0.024198
2020-05-21 -0.007455 -0.018619 -0.012011 -0.002787
2020-05-22  0.006438 -0.006128  0.000436  0.005432
2020-05-26 -0.006774  0.028465 -0.010572  0.004679

In [119]:
In [244]: returns['MSFT'].corr(returns['IBM'])

0.5980120236275744

In [120]:
In [245]: returns['MSFT'].cov(returns['IBM'])

0.00016231409041853067

In [121]:
In [246]: returns.MSFT.corr(returns.IBM)

0.5980120236275744

In [122]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.532162  0.711200  0.642323
IBM   0.532162  1.000000  0.598012  0.528959
MSFT  0.711200  0.598012  1.000000  0.750967
GOOG  0.642323  0.528959  0.750967  1.000000

In [123]:
In [248]: returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000328  0.000152  0.000222  0.000199
IBM   0.000152  0.000249  0.000162  0.000143
MSFT  0.000222  0.000162  0.000296  0.000221
GOOG  0.000199  0.000143  0.000221  0.000293

In [124]:
In [249]: returns.corrwith(returns.IBM)

AAPL    0.532162
IBM     1.000000
MSFT    0.598012
GOOG    0.528959
dtype: float64

In [125]:
In [250]: returns.corrwith(volume)

AAPL   -0.140947
IBM    -0.105005
MSFT   -0.066476
GOOG   -0.038548
dtype: float64

In [126]:
In [263]: data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
   .....:                      'Qu2': [2, 3, 1, 2, 3],
   .....:                      'Qu3': [1, 5, 2, 4, 4]})

In [264]: data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [127]:
In [265]: result = data.apply(pd.value_counts).fillna(0)

In [266]: result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0